dataset_name: 'MNIST'
train_batch_size: 64
learning_rate: 1.0e-3
num_epochs: 10
input_size: [28,28]
input_channels: 1
channels: 3
layers_num_range: [2, 8]
kernel_size: 3
classes: 10
save_model_path_prefix: './models_chkps/mnist_change_layers'
save_results_path: './results/mnist_change_layers.json'
save_figs_path: './figures/mnist_change_layers.pdf'
legend_title: '$L$ (num of layers)'
exp_type: 'change layers num'