dataset_name: 'FashionMNIST'
train_batch_size: 64
learning_rate: 1.0e-3
num_epochs: 10
input_size: [28,28]
input_channels: 1
channels: 6
layers_num: 4
kernel_size_range: [2, 3, 4, 5]
classes: 10
save_model_path_prefix: './models_chkps/fashion_mnist_change_kers'
save_results_path: './results/fashion_mnist_change_kers.json'
save_figs_path: './figures/fashion_mnist_change_kers.pdf'
legend_title: '$k$ (kernel size)'
exp_type: 'change kernel size'